### ISSUE TITLE
https://api.msrc.microsoft.com/cvrf/v2.0/swagger/index returning 503

### ISSUE THREAD

**Issue by grant-cameron** [microsoft/MSRC-Microsoft-Security-Updates-API#105]
All calls to the api currently are returning 503 errors for me and others.

**Comment by HanieSolaty** [comment]
I'm having the exact same issue now and 4 month has passed since the last post, so is this ever gonna be fixed?

**Comment by msft-tsharp** [comment]
Sorry for the delay in response - the API/Swagger pages are currently online!
