### ISSUE TITLE
APIs in python

### ISSUE THREAD

**Issue by amankumarchagti** [microsoft/MSRC-Microsoft-Security-Updates-API#106]
How can I use MSRCSecurityupdates APIs in python to pll Microsoft update data and bulletin?

**Comment by p0w3rsh3ll** [comment]
Yes, of course.

**Comment by amankumarchagti** [comment]
how can I use that? any documentation

**Comment by p0w3rsh3ll** [comment]
On the page https://msrc.microsoft.com/update-guide/en-us at the top, there's a developer button/tab that points to https://api.msrc.microsoft.com/cvrf/v2.0/swagger/index

**Comment by amankumarchagti** [comment]
got ya. Thanks :)
