### ISSUE TITLE
Create New Key is failing

### ISSUE THREAD

**Issue by amuodd** [Microsoft/MSRC-Microsoft-Security-Updates-API#11]
When I click on Create New Key on the API site, I'm directed to login with my microsoft account (using a corporate account), which I do, and then I get redirected back to the "Create New Key" page, and nothing seems to have happened

**Comment by craig-martin** [comment]
Doh!  Sorry you're having issues creating an API key.  API keys are managed by the Security Update Guide.  Please post to community forum for the Security Update Guide for help:
https://social.technet.microsoft.com/Forums/security/en-us/home?forum=securityupdateguide
