### ISSUE TITLE
Regarding https://api.msrc.microsoft.com/sug/v2.0/

### ISSUE THREAD

**Issue by sukeshleel** [microsoft/MSRC-Microsoft-Security-Updates-API#112]
Can we use the this API URL to get data "https://api.msrc.microsoft.com/sug/v2.0/en-us/affectedProduct?%24orderBy=releaseDate+desc&%24filter=%28releaseDate+gt+2022-11-01T00%3A00%3A00%2B05%3A30%29+and+%28releaseDate+lt+2022-11-30T23%3A59%3A59%2B05%3A30%29" 

because above mentioned API URL gives better and easy way of data then the other API URL which is https://api.msrc.microsoft.com/cvrf/v2.0/cvrf/2022-nov

**Comment by p0w3rsh3ll** [comment]
I'd say, yes you can as long as it works :-)
api.msrc.microsoft.com/**sug** is probably what the https://msrc.microsoft.com/update-guide/ uses. 
SUG means Security Update Guide. You can fork the module, make all the changes you want to meet your needs and use it.

The current module uses the Rest API documented and its official URL: [https://api.msrc.microsoft.com/cvrf/v2.0](https://api.msrc.microsoft.com/cvrf/v2.0). 
It's defined in the following file: https://github.com/microsoft/MSRC-Microsoft-Security-Updates-API/blob/main/src/MsrcSecurityUpdates/Private/Set-GlobalVariables.ps1
The current module needs to remain on the "official" track.

**Comment by msft-tsharp** [comment]
@p0w3rsh3ll you're correct - technically you can use the api but we do not have any guarantees or official support for the api as it's not currently our public / documented API. Just keep that in mind when using those endpoints as they're likely to change over time.

With that said, use `https://api.msrc.microsoft.com/sug/v2.0/en-US` to retrieve content that is localized. There are other supported languages, but this is the default one.
