### ISSUE TITLE
Sept 12th after release, API didn't return full set of MSRC data

### ISSUE THREAD

**Issue by fredthedop** [microsoft/MSRC-Microsoft-Security-Updates-API#122]
On September 12th, after the Microsoft Patch Tuesday release, the API route "https://api.msrc.microsoft.com/cvrf/v2.0/document/2023-Sep" only returned the list of Edge Chromium updates. It did not list anything else (OS, IE, .NET, Office, etc updates) until nearly 3 hours after the release. During this same period of time, however, the MSRC website did properly list all the updates.

**Comment by vishparekh** [comment]
The updates to the API route were delayed for ~1 hour on September 12th.

**Comment by fredthedop** [comment]
Respectfully, it appears it was a lot longer than an hour. The MSRC notification email arrived in my mailbox at 12:20 Central. The data was already available on the MSRC before this email was sent or arrived. However, the API didn't return the full list until 14:40 Central. So that is at least 2 hours and 20 minutes. Not 1 hour. It is even more, when one considers that the MSRC was actually updated before the MSRC email notification was sent.

**Comment by vishparekh** [comment]
Thank you for bringing this to our attention. Yes, we have already fixed the root cause of this issue to prevent this from happening in the future.
