### ISSUE TITLE
/v3.0/cvrf/<ID> returns xml not json

### ISSUE THREAD

**Issue by ByamB4** [microsoft/MSRC-Microsoft-Security-Updates-API#146]
When using v2 endpoint `https://api.msrc.microsoft.com/cvrf/v3.0/cvrf/${lastItem["ID"]}` it returns list of json data of month. But in newer version of endpoint only returns **xml** data. And provided swagger there is no option to select **json** and **xml**. How do I get **json** data.

For example:
  - `https://api.msrc.microsoft.com/cvrf/v3.0/cvrf/2024-May`

**Comment by MateuszBelczowski** [comment]
You can control the returned format using `Accept` HTTP header. By default it returns XML, but if you specify header as `Accept: application/json` you should get a response in a JSON format.

**Comment by ByamB4** [comment]
Damn i'm so noob, thanks
