### ISSUE TITLE
Cannot generate an API key

### ISSUE THREAD

**Issue by redbaron4** [microsoft/MSRC-Microsoft-Security-Updates-API#15]
I could not finda place to post this so I am posting this here. The [developer tab](https://portal.msrc.microsoft.com/en-us/developer) has a button "Create New Key". When I am logged in and I click on the link, it redirects me to login again and after log-in takes me to "Guidance" tab. I can't generate or view my key.
Do I need a special account or something to generate a key? How do I register for such an account?

**Comment by IrootGeek** [comment]
HI @redbaron4  
I have the same problem i can't get my API KEY,

**Comment by pombredanne** [comment]
Same here. It is impossible to obtain an API key once logged in.

**Comment by craig-martin** [comment]
Doh! Sorry you're having issues creating an API key. API keys are managed by the Security Update Guide. Please post to community forum for the Security Update Guide for help:
https://social.technet.microsoft.com/Forums/security/en-us/home?forum=securityupdateguide

**Comment by ms-AlexDavis** [comment]
I was able to reproduce the issue, This is not related to the project (MSRC portal is separate, bugs can be submitted [here](https://social.technet.microsoft.com/Forums/security/en-us/home?forum=securityupdateguide) ), however since it affects the script in the repo im going to leave the issue open to track / provide updates on this.

An internal bug report has been filed, and the reliant team has been made aware. Sorry about the inconvenience.

**Comment by pombredanne** [comment]
@ms-AlexDavis Thanks for following up on this

**Comment by pombredanne** [comment]
For reference this seems like this a problem for everyone and pretty much ever since this came up live at least since April 18th e.g. pretty since this API was announced 

 https://social.technet.microsoft.com/Forums/sharepoint/en-US/d44f5fff-c59c-426e-bc0b-b95647adb16a/api-key-generate-problems-security-update-guide-developer-page?forum=securityupdateguide

**Comment by pombredanne** [comment]
@craig-martin FWIW there are posts in your forums that have gone unanswered since April 18th. It would be nice not to close this ticket until this is resolved.  This is impacting real projects and real team that depend on these projects: See https://github.com/cve-search/VIA4CVE/issues/3

**Comment by redbaron4** [comment]
@ms-AlexDavis Thanks for this.

I have added some more information on the forum at https://social.technet.microsoft.com/Forums/security/en-US/32870be0-8b8e-4cde-9dc6-c9bf0b82f09d/cannot-generate-an-api-key-for-security-update-guide-api-access?forum=securityupdateguide#32870be0-8b8e-4cde-9dc6-c9bf0b82f09d

Also FWIW, a colleague of mine used his outlook account to log-in and could succesfully generate a key, so I suspect the issue is with accounts that are created using external email IDs (e.g. gmail)

**Comment by ms-AlexDavis** [comment]
Ok, so status update as of last night / this morning...

Certain accounts are failing to log into the Developer area of the Security Update Guide. As an immediate workaround, you can use an existing live.com, outlook.com, or Microsoft.com email address. If you do not already have an email address that ends with one of these domains, we suggest you create an Outlook account here (https://outlook.live.com/) and use that to log in. If you have any other issues with logging in, please reply to this issue and we will be happy to assist. Thank you for your patience while we investigate this behavior.

-The MSRC Dev team

**Comment by pombredanne** [comment]
@ms-AlexDavis Thanks!
I question the whole idea to have a requirement to authenticate when the same data is also available publicly. This makes the things more difficult for open source consumers like @cve-search

**Comment by pombredanne** [comment]
@ms-AlexDavis Any update?

**Comment by ms-AlexDavis** [comment]
@pombredanne Sorry for the long delay. The team responsible for the portal is still working on this. Due to testing, updates are rolled out fairly slowly, so while the issue is being looked into, it will take some time for any roll out.  For now, using an @outlook.com or @live.com email to sign in looks like the only short term solution. 

I will update more when I hear more from the portal team.

**Comment by msenturk** [comment]
I just created new email address outlook.com for it  but even with this new outlook.com address I cant get/generate API Key.

**Comment by JonathanThorpe** [comment]
I seem to be having trouble with this too - just signed up for a brand new @outlook.com email address and it doesn't seem to work - even going InCognito to ensure that there's nothing else interfering with this.

Is there a workaround to this?

**Comment by pombredanne** [comment]
@JonathanThorpe Not that I know of. I went through the same issues as you did with a fresh outlook.com email

**Comment by rakeshrm** [comment]
I faced the same issue with outlook.com email address too, the following workaround fixed it:
(putting it here, in case it helps someone)

- Remove the MSRC application's authorization from the email account
  For outlook.com email: Edit Profile > Privacy > Apps and services.
  Click 'Edit' for MSRC Portal and "Remove These Permissions"

- Make sure the email account has a name associated to it (Not sure if this was really needed)
- Go to the MSRC portal and sign-in again using the same account (Need to provide the permissions again)
- Now create your API from the developer tab.

**Comment by ryvius** [comment]
@rakeshrm yes the name is important. I updated the first name and last name and was able to create the API key.

**Comment by pombredanne** [comment]
Going through all these hooks and crannies sounds like a counter productive move to me... Is this going to stay this way?

**Comment by FelisaLDore** [comment]
There are various ways to create the API key. Online help is a great source but where to access is the issue. Developing new API key is not an hinderance if know where to get it easily. Mark the steps! Ine can take help from allkeysgenerator.com for getting any type of keys. This forum can help reach to the solution.

**Comment by C0FFEEC0FFEE** [comment]
I just ran into the same problem. I registered a new outlook.com e-mail address and the [website for requesting an API key](https://portal.msrc.microsoft.com/en-us/developer) was running in circles (login, request, login, request, login, ...).
After setting the name field via [account.microsoft.com](https://account.microsoft.com/) i was able to request the API key.

I added a hint to the README.

**Comment by Krytical13** [comment]
I use my Work domain Azure/365 account for most everything.
So at this point, is it impossible to sign up for an API key using a company domain Azure/365 account?

**Comment by mdressman** [comment]
Hello @Krytical13, unfortunately yes you'll need an MSA. Enterprise accounts are not supported. 

The good news for all is we are actively working on removing the authorization and API key requirements.. We will share updates before the end of year.

**Comment by mdressman** [comment]
Thank you all for the feedback, we no longer require an API Key or authentication to use the API.
