### ISSUE TITLE
Non-standard CVRF elements

### ISSUE THREAD

**Issue by vincep5** [Microsoft/MSRC-Microsoft-Security-Updates-API#18]
RestartRequired and the newer SubType elements are not part of the standard CVRF schema.  There should be an update to the community that new types are being added to the XML and JSON feed.  The swagger files have not been updated either to reflect this.

**Comment by ms-AlexDavis** [comment]
Will update swagger by Monday.

**Comment by ms-AlexDavis** [comment]
Swagger has been updated. We will start announcing field changes in the readme.md as well for viability.
