### ISSUE TITLE
Error when using API to retrieve data: impact contains NONE, and some KB links have no description and wrong matching

### ISSUE THREAD

**Issue by michaelhku2002** [microsoft/MSRC-Microsoft-Security-Updates-API#28]
Dear all,

I'm responsible to debug for the python program to retrieve data of "Patch Tuesday" for Microsoft updates. The most serious problems are 

- Impact of the vulnerability for the product contains NONE
- Some KB links have no description
- Some KB links have wrong matches i.e. the URL for the KB does not match the KB's title

So, I wish to know what the problem is related to? Thanks!

**Comment by craig-martin** [comment]
Thanks for the feedback!  Responses below...

> Impact of the vulnerability for the product contains NONE

This can happen if the fix is Defense in Depth
> Some KB links have no description 

Can you please provide an example? 

>Some KB links have wrong matches i.e. the URL for the KB does not match the KB's title 

Probably a bug in our data, can you provide examples for us to investigate?

**Comment by michaelhku2002** [comment]
Hi @craig-martin, so for your reply

"This can happen if the fix is Defense in Depth"
But I wish to prevent it from being shown, how can I do for this?

About the problems related to KB links got from the API, please have a look below

For no description:
SQL server
<li><a href="" target="_blank">KB4056895<span></span></a></li>
Windows
<li><a href="" target="_blank">KB4056895<span></span></a></li>
Microsoft Office
<li><a href="" target="_blank">KB4011637<span></span></a></li>
<li><a href="" target="_blank">KBClick to Run<span></span></a></li>
<li><a href="" target="_blank">KB4011636<span></span></a></li>
<li><a href="" target="_blank">KB4011651<span></span></a></li>
<li><a href="" target="_blank">KB4011639<span></span></a></li>
Developer tools
<li><a href="" target="_blank">KB4055001<span></span></a></li>
<li><a href="" target="_blank">KB4056895<span></span></a></li>
<li><a href="" target="_blank">KB4054993<span></span></a></li>
Browser
<li><a href="" target="_blank">KB4056895<span></span></a></li>

KB links with wrong matches
Developer tools
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055266" target="_blank">KB4054999<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055265" target="_blank">KB4054994<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055270" target="_blank">KB4054181<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055269" target="_blank">KB4054183<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055272" target="_blank">KB4054174<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055269" target="_blank">KB4054176<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055266" target="_blank">KB4054993<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055266" target="_blank">KB4055001<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055271" target="_blank">KB4054182<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055271" target="_blank">KB4054170<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055272" target="_blank">KB4054172<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055270" target="_blank">KB4054171<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055267" target="_blank">KB4055002<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055270" target="_blank">KB4054175<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055265" target="_blank">KB4054997<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055271" target="_blank">KB4054177<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055267" target="_blank">KB4054996<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055532" target="_blank">KB4054995<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055265" target="_blank">KB4055000<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055269" target="_blank">KB4054172<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055532" target="_blank">KB4074880<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055267" target="_blank">KB4054995<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055532" target="_blank">KB4054998<span></span></a></li>
<li><a href="https://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4055272" target="_blank">KB4054183<span></span></a></li>

By the way, I've found something strange as following examples:
<li><a href="https://github.com/PowerShell/Announcements/issues/3" target="_blank">KBRelease Notes<span></span></a></li>
<li><a href="https://github.com/aspnet/Announcements/issues/284" target="_blank">KBCommit<span></span></a></li>
<li><a href="https://github.com/Microsoft/ChakraCore/releases/tag/v1.7.6" target="_blank">KBCommit<span></span></a></li>

All the above links are the results got from the API, so please help to see what happened in the API to cause the above errors. Thanks!
