### ISSUE TITLE
API endpoints should set CORS headers and respond to OPTIONS requests

### ISSUE THREAD

**Issue by mattfoster** [Microsoft/MSRC-Microsoft-Security-Updates-API#3]
Apologies if this is the wrong place to report this sort of feature request. Please let me know if I should file this elsewhere.

It would be very useful if the API endpoints supported CORS, as this would allow data to be easily consumed by client-side web applications.

As things currently stand attempting to use an `XMLHttpRequest` requires adding the `api-key` header which (at least in Chome) triggers an a pre-flight OPTIONS request. This returns a 404 status, and does not contain an `Access-Control-Allow-Origin` header, which blocks further requests from being made.

Here's the chrome console when this occurs:
![](https://dl.dropboxusercontent.com/s/uvjnw2v81xbknra/2017-04-13%20at%2009.09.png)

Here's an example OPTIONS request which fails: 

```
$ curl "https://api.msrc.microsoft.com/Updates?api-version=2016-08-01" -H 'api-key: xxxx' -X OPTIONS
{ "statusCode": 404, "message": "Resource not found" }
```

It would be great if you would consider adding support for this.

**Comment by ms-AlexDavis** [comment]
Feature requests for the API its self can be posted in the technet forums, found here: https://social.technet.microsoft.com/Forums/security/en-us/home?forum=securityupdateguide
