### ISSUE TITLE
Supersede is misspelled in the remediation API

### ISSUE THREAD

**Issue by jeremy-hanna** [Microsoft/MSRC-Microsoft-Security-Updates-API#32]
Supersede is a [commonly misspelled word](https://en.wikipedia.org/wiki/Commonly_misspelled_English_words#R%E2%80%93S) and has been misspelled in the [swagger files](https://github.com/Microsoft/MSRC-Microsoft-Security-Updates-API/blob/master/docs/swagger.yaml#L328)

With the next minor patch release (as this is an API breaking change), can we fix this?

Sorry about being a grammar nazi 😄

**Comment by craig-martin** [comment]
Thanks for pointing this out and correcting the code, just waiting on the Contributor License Agreement.

**Comment by jeremy-hanna** [comment]
Whoops, sorry 👍 

Thank you!
