### ISSUE TITLE
Get-MsrcCvrfDocument Not working

### ISSUE THREAD

**Issue by uwanve** [Microsoft/MSRC-Microsoft-Security-Updates-API#37]
PS C:\WINDOWS\system32> Get-MsrcCvrfDocument -ID '2017-Apr'
Get-MsrcCvrfDocument : Cannot retrieve the dynamic parameters for the cmdlet. Unable to get online
the list of CVRF ID
At line:1 char:1
+ Get-MsrcCvrfDocument -ID '2017-Apr'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-MsrcCvrfDocument], ParameterBindingExcepti
   on
    + FullyQualifiedErrorId : GetDynamicParametersException,Get-MsrcCvrfDocument

**Comment by barborico** [comment]
This was a temporary API outage, so it should be working now. Sorry for the inconvenience!

**Comment by ESL482** [comment]
Hi  , i am also getting the same error from the last 3days...please help to solve this  asap... 

below is the error :
 **Get-MsrcCvrfDocument -ID $monthOfInterest -Verbose | Get-MsrcSecurityBulletinHtml -Verbose | Out-File c:\temp\MSRCAprilSecurityUpdates.html**
Get-MsrcCvrfDocument : Cannot retrieve the dynamic parameters for the cmdlet. Unable to get online the list of CVRF ID
At line:1 char:1
+ Get-MsrcCvrfDocument -ID $monthOfInterest -Verbose | Get-MsrcSecurity ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-MsrcCvrfDocument], ParameterBindingException
    + FullyQualifiedErrorId : GetDynamicParametersException,Get-MsrcCvrfDocument

**Comment by msrcgit** [comment]
Could be an issue with your API key.  Try this:

``` powershell
Set-MSRCApiKey

Get-MsrcSecurityUpdate -Year 2019
```

If you run into problems, try to regenerate your API key by visiting:
https://portal.msrc.microsoft.com/en-us/developer
