### ISSUE TITLE
GetDynamicParametersException,Get-MsrcCvrfDocument  

### ISSUE THREAD

**Issue by ESL482** [Microsoft/MSRC-Microsoft-Security-Updates-API#44]
Hi , i am  getting the same error from the last 3days...please help to solve this asap...

This is for March -2019

below is the error :
**Get-MsrcCvrfDocument -ID $monthOfInterest -Verbose | Get-MsrcSecurityBulletinHtml -Verbose | Out-File c:\temp\MSRCMarchSecurityUpdates.html**
Get-MsrcCvrfDocument : Cannot retrieve the dynamic parameters for the cmdlet. Unable to get online the list of CVRF ID
At line:1 char:1

Get-MsrcCvrfDocument -ID $monthOfInterest -Verbose | Get-MsrcSecurity ...
  + CategoryInfo          : InvalidArgument: (:) [Get-MsrcCvrfDocument], ParameterBindingException
  + FullyQualifiedErrorId : GetDynamicParametersException,Get-MsrcCvrfDocument

**Comment by msrcgit** [comment]
Replied to #37 also:

Could be an issue with your API key.  Try this:

``` powershell
Set-MSRCApiKey

Get-MsrcSecurityUpdate -Year 2019
```

If you run into problems, try to regenerate your API key by visiting:
https://portal.msrc.microsoft.com/en-us/developer

**Comment by ESL482** [comment]
Thank you so much - :) ...after doing above procedure it worked fine
