### ISSUE TITLE
Updates API OData is not working since last week

### ISSUE THREAD

**Issue by vincep5** [microsoft/MSRC-Microsoft-Security-Updates-API#47]
When I try running this : `https://api.msrc.microsoft.com/Updates?api-version=2019&$filter=CurrentReleaseDate gt 2019-10-01`
it returns
`{
    "error": {
        "code": "",
        "message": "OData URI failed validation"
    }
}`
This was working fine, but have noticed this week the failure.
Swagger and documentation on the API mentioned that OData is supported

**Comment by craig-martin** [comment]
This is supposed to work, the examples in the docs and tests show this functionality.
I can repro:

``` powershell
Import-Module -Name MsrcSecurityUpdates

Set-MSRCApiKey -ApiKey 'this is not the key'

Get-MsrcSecurityUpdate -Before 2017-01-01 -Verbose
```

Produces this error:
```
VERBOSE: Calling https://api.msrc.microsoft.com/Updates?$filter=CurrentReleaseDate lt 2017-01-01&api-version=2016-08-01
VERBOSE: GET https://api.msrc.microsoft.com/Updates?$filter=CurrentReleaseDate lt 2017-01-01&api-version=2016-08-01 with 0-byte payload
Get-MsrcSecurityUpdate : HTTP Get failed with status code BadRequest: Bad Request
```

**Comment by vincep5** [comment]
Thanks for looking, will it be planned to be corrected so that it works again ?

**Comment by wedge905** [comment]
Yes, turns out it's broken due to some dependency updates.  We'll get a fix out asap.

**Comment by wedge206** [comment]
Yes, turns out it's broken due to some dependency updates.  We'll get a fix out asap.

**Comment by vincep5** [comment]
any estimated time on the fix?
