### ISSUE TITLE
Cannot generate API

### ISSUE THREAD

**Issue by Henrikcj** [microsoft/MSRC-Microsoft-Security-Updates-API#53]
The webside is looping. I did try to greate a new user, but i still cant get an APi key.

**Comment by vanderpot-uber** [comment]
Looks like the website is broken right now. I was able to sign up at 
https://msrcapi.portal.azure-api.net/signup
then go to
https://msrcapi.portal.azure-api.net/products/57aa15eabe8da012d063d0e6/subscribe

Cheers!

**Comment by mdressman** [comment]
Thank you for the feedback, we no longer require an API Key or authentication to use the API.
