### ISSUE TITLE
Long Term Support

### ISSUE THREAD

**Issue by vanderpot-uber** [microsoft/MSRC-Microsoft-Security-Updates-API#54]
Hi MSRC Team,

We're interested in integrating this API in our security systems. The content provided by this API is well-structured and will help us with vulnerability management. We had a few questions about MSRC's support of this API:

What are the plans for long term support of this API?
Does this API follow a versioning scheme?
Are there any other APIs available for security information from Microsoft?

Thanks,
Alex

cc: @wedge206  @mdressman

**Comment by gusnaughton** [comment]
i am also interested in this

**Comment by mdressman** [comment]
Hello, thanks for reaching out. We are committed to long-term support for this API. There's not currently versioning but we will be introducing a v2 (and continuing to iterate on new versions from there) in the coming months. We will share updates on this repo as well as the MSRC blog and twitter when the new versions are ready. 

Regarding other APIs, you could check out the [Microsoft Security Graph API](https://www.microsoft.com/en-us/security/business/graph-security-api), though unrelated to this service.
