### ISSUE TITLE
MSRC Security Updates API returning 'Internal Server Error' 500

### ISSUE THREAD

**Issue by ian-mv** [microsoft/MSRC-Microsoft-Security-Updates-API#59]
We've been using the MSRC Security Updates API for a while to get security updates information. However, the API has been returning 'Internal Server Error' 500 since today (04/23/2020).

Is the API down? Has there been any change recently in usage instructions? Any other ideas why this error might be thrown?

url: https://api.msrc.microsoft.com/cvrf/2020-apr?api-version=2016

We've verified that the api key sent in the request header is valid.

![msrc_api_error](https://user-images.githubusercontent.com/57635455/80151821-43525a00-8580-11ea-9657-af55505cd1d9.png)

**Comment by mdressman** [comment]
Thanks for reaching out, this is resolved and the API is accessible, please let us know if you have any issues

**Comment by ian-mv** [comment]
Thanks @mdressman . I can confirm that we're able to access the API again.
