### ISSUE TITLE
MSRC Security Updates API returning 'Internal Server Error' 500

### ISSUE THREAD

**Issue by zito284** [microsoft/MSRC-Microsoft-Security-Updates-API#62]
Hi MSRC team,
Is the API currently down? I just test the API and it is returning Internal Server Error 500. 
Is there any maintenance running?
url: https://api.msrc.microsoft.com/cvrf/2020-jul?api-version=2016
I can verify that the api key sent in the request header is valid.
![image](https://user-images.githubusercontent.com/17568452/90620179-4f9fa880-e23c-11ea-9498-05b3e4c9139a.png)

**Comment by C0FFEEC0FFEE** [comment]
Same here:
```
curl -X GET "https://api.msrc.microsoft.com/Updates?api-version=2018" -H "accept: application/json" -H "api-key: changeme"
{"error":{"code":"","message":"An error has occurred."}}
```

This still worked last night at 0300 UTC.

**Comment by mdressman** [comment]
This is resolved. Sorry about the inconvenience.
