### ISSUE TITLE
Identifying Master KB Number

### ISSUE THREAD

**Issue by ir8d0g** [Microsoft/MSRC-Microsoft-Security-Updates-API#7]
I welcome being mistaken, but it doesn't appear that the master KB is attainable unless I scrape it out of the URL field of the "Known Issue" property of a vulnerability remediation.

Is there an easier way to get the master KB?

**Comment by filiphhh** [comment]
The KB number is specified in a the Description field of the remediation.

The following will list all KB numbers contained within an update:

```
$Update = Get-MsrcSecurityUpdate -After (Get-Date).AddMonth(-1)
(Get-MsrcCvrfDocument -Id $Update).Vulnerability.Remediations.Description.Value |? {$_ -Match '^\d+$'} | Select -Unique | Sort-object |% {"KB$_"}
```
