### ISSUE TITLE
Microsoft Docs: Bookmarks option and Collection total percentage gone

### ISSUE THREAD

**Issue by RobMulder** [microsoft/MSRC-Microsoft-Security-Updates-API#99]
This is not about bookmarks in Browsers but the bookmarks in my Docs account.
They do exist if I go directly to: https://docs.microsoft.com/en-us/users/username**/bookmarks**.
But in the menu or clicking on photo the shortcuts to Bookmarks are gone.

In a Collection was a Total Percentage done counter, that's gone too...

Please add those back!

![Capture1](https://user-images.githubusercontent.com/37290742/118137684-c94c7780-b405-11eb-93eb-d1b75eca047e.JPG)
![Capture2](https://user-images.githubusercontent.com/37290742/118137691-cbaed180-b405-11eb-9154-e7c6b6e36c26.JPG)
![Capture3](https://user-images.githubusercontent.com/37290742/118137699-cd789500-b405-11eb-89de-7a46a9bec2d2.JPG)

Regards,
Rob Mulder

**Comment by RobMulder** [comment]
bump?

**Comment by p0w3rsh3ll** [comment]
This repository is about the MSRC API PowerShell module.
It's not related to docs.microsoft.com and cannot provide help about your Bookmark issue.
